<a href="https://colab.research.google.com/github/ruhaan-ai/Numpy/blob/main/array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4,5,])
a2 = np.array([6,7,8,9,10])

In [4]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [5]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [6]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [9]:
l = [10,20,30,40,50]
arr = np.array(l)

In [10]:
arr + 10

array([20, 30, 40, 50, 60])

In [11]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [13]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
slice = a[:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [15]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [17]:
A

array([[1, 2],
       [3, 4]])

In [18]:
B

array([[5, 6],
       [7, 8]])

In [19]:
A @ B

array([[19, 22],
       [43, 50]])

In [20]:
A.T

array([[1, 3],
       [2, 4]])